spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}



  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
  application:
    name: auth-service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info ,loggers

logging:
  file:
    path: ${LOG_PATH}
