# =======================
# Application Settings
# =======================
spring.application.name=event-service

# =======================
# MongoDB Configuration
# =======================
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=eventdb
spring.mongodb.username=admin
spring.mongodb.password=admin

# =======================
# Server Configuration
# =======================
server.port=8082

# =======================
# Logging Configuration
# =======================
logging.level.org.springframework.data.mongodb.core=DEBUG

# =======================
# Actuator / Management
# =======================
management.endpoints.web.exposure.include=health,info,loggers